spring:
  cloud:
    aws:
      credentials:
        accessKey: test
        secretKey: test
      region:
        static: ap-northeast-2
      s3:
        bucket: module
    gcp:
      project-id:
      credentials:
        json-path:
      bucket: