spring:
  config:
    import:
      - "application-jwt.yml"
      - "application-file.yml"
      - "application-redis.yml"
      - "application-swagger.yml"
      - "application-persistence.yml"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    enable:
      jvm: true
      gc: true
      memory: true
      processors: true
      files: true
      loggers: true
      tomcat: true

logging:
  level:
    org.springframework: INFO